[package]
name = "draft"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"

[dependencies]
petgraph = "*"
either = "*"
itertools = "*"
clap = { version = "4.5.32", features = ["derive"] }
